linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - exportloopref # deprecated
    - gomnd # deprecated
    - exhaustruct
    - gochecknoglobals
    - wrapcheck
    - testpackage
    - depguard
    - err113
linters-settings:
  gofumpt:
    extra-rules: true
  varnamelen:
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - tt
      - t
