linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - exportloopref # deprecated
    - gomnd # deprecated
    - exhaustruct
    - gochecknoglobals
linters-settings:
  gofumpt:
    extra-rules: true
  varnamelen:
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - tt
      - t
  depguard:
    rules:
      main:
        files:
        - $all
        - "!$test"
        allow:
        - $gostd
        - github.com/samber/slog-multi
        - github.com/rs/zerolog
        - github.com/samber/slog-zerolog/v2
        - github.com/oscarbc96/agbridge/pkg
        deny:
        - pkg: "github.com/pkg/errors"
          desc: Should be replaced by standard lib errors package
      test:
        files:
        - $test
        allow:
        - $gostd
        - github.com/stretchr/testify
