# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agbridge < Formula
  desc "agbridge CLI for forwarding requests to private API gateways in AWS."
  homepage "https://github.com/oscarbc96/agbridge"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.2/agbridge_Darwin_x86_64.tar.gz"
      sha256 "9544e2e5611f6b23c104fd3f6e1a19d4e49bcf97d57bd2e1c248db6f307db840"

      def install
        bin.install "agbridge"
      end
    end
    on_arm do
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.2/agbridge_Darwin_arm64.tar.gz"
      sha256 "c4fc4592c5fa185075575566040aed4ef9889c9feb4a5ef292fab3d5d8f78049"

      def install
        bin.install "agbridge"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.2/agbridge_Linux_x86_64.tar.gz"
        sha256 "0ddf7e849c5e4e8125d3cc4f68e60ca73cc313f8e1583d0410e5f11dae6e201b"

        def install
          bin.install "agbridge"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.2/agbridge_Linux_arm64.tar.gz"
        sha256 "8ce2af73e493438cf5d9a66e06b78429e491ec86684c09c902ac6b6672ea8273"

        def install
          bin.install "agbridge"
        end
      end
    end
  end

  test do
    system "#{bin}/agbridge --version"
  end
end
