# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agbridge < Formula
  desc "agbridge CLI for forwarding requests to private API gateways in AWS."
  homepage "https://github.com/oscarbc96/agbridge"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.12/agbridge_Darwin_x86_64.tar.gz"
      sha256 "b39c7fdf2f230326c9ddd8495b03165461956e2b6eef40a9890e32943cf65739"

      def install
        bin.install "agbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.12/agbridge_Darwin_arm64.tar.gz"
      sha256 "3eead6080c15c234dc6f41b6d4f7bb2240452f9c2c78231b527787bd39cfce20"

      def install
        bin.install "agbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.12/agbridge_Linux_x86_64.tar.gz"
      sha256 "da53d16774ec55f9cf6f314e18fcb2accf583bfd016ca2e013e83f8906be555c"
      def install
        bin.install "agbridge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.12/agbridge_Linux_arm64.tar.gz"
      sha256 "75bfde35a3510b054a11df92d13ee8ce824914c733b67a93d2a0a27dada77096"
      def install
        bin.install "agbridge"
      end
    end
  end

  test do
    system "#{bin}/agbridge --version"
  end
end
