# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agbridge < Formula
  desc "agbridge CLI for forwarding requests to private API gateways in AWS."
  homepage "https://github.com/oscarbc96/agbridge"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.7/agbridge_Darwin_x86_64.tar.gz"
      sha256 "d989202e387ca1acd2f239043fd8906c352d5231196b99eced03e29266292764"

      def install
        bin.install "agbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.7/agbridge_Darwin_arm64.tar.gz"
      sha256 "6ea7d98022aa71cdcaa047d8e1ac9d3fcc90be05fd8bd9c64b099f8805582062"

      def install
        bin.install "agbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.7/agbridge_Linux_x86_64.tar.gz"
      sha256 "6a01164f91a9abc86965ce03d117d353e0cf1bc1ded798518e7bdd1010932581"
      def install
        bin.install "agbridge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/oscarbc96/agbridge/releases/download/v0.0.7/agbridge_Linux_arm64.tar.gz"
      sha256 "56c3170faddb4d8c16995a93687fd0ca053c071b29e35f3b13e717c0df5f1710"
      def install
        bin.install "agbridge"
      end
    end
  end

  test do
    system "#{bin}/agbridge --version"
  end
end
