name: test

on: pull_request

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname
        env:
          AWS_ACCESS_KEY_ID: default
          AWS_SECRET_KEY: default
      - uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86  # v2.4.0
        with:
          paths: "unit-tests.xml"
        if: always()
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          args: build --clean --snapshot --single-target
